import { describe, it, expect } from 'vitest'
import { isPhantomTranscript, calculatePcm16Rms, isSpeechAudio, transcribe } from './asr.js'

describe('ASR Phantom Transcription & Speech Energy Filter', () => {
  it('detects phantom transcriptions hallucinated from silence/noise', () => {
    // Known phantom words/phrases reported by users or generated by STT on background noise
    expect(isPhantomTranscript('Greț')).toBe(true)
    expect(isPhantomTranscript('Greț.')).toBe(true)
    expect(isPhantomTranscript('gret')).toBe(true)
    expect(isPhantomTranscript('Subtitrare în limba română')).toBe(true)
    expect(isPhantomTranscript('Subtitrarea în limba română.')).toBe(true)
    expect(isPhantomTranscript('Subtitrări')).toBe(true)
    expect(isPhantomTranscript('Vizionare plăcută!')).toBe(true)
    expect(isPhantomTranscript('Mulțumesc.')).toBe(true)
    expect(isPhantomTranscript('Vă mulțumesc.')).toBe(true)
    expect(isPhantomTranscript('To be continued')).toBe(true)
    expect(isPhantomTranscript('   ')).toBe(true)
    expect(isPhantomTranscript('.')).toBe(true)
  })

  it('allows valid speech transcriptions', () => {
    expect(isPhantomTranscript('Salut, ce mai faci?')).toBe(false)
    expect(isPhantomTranscript('Vreau o cafea fără zahăr.')).toBe(false)
    expect(isPhantomTranscript('Cum este vremea azi afară?')).toBe(false)
    expect(isPhantomTranscript('Deschide setările te rog')).toBe(false)
  })

  it('calculates RMS energy correctly for PCM 16-bit audio', () => {
    // Silence buffer (all zeros)
    const silenceBuf = Buffer.alloc(1600) // 100ms at 8kHz 16-bit
    expect(calculatePcm16Rms(silenceBuf)).toBe(0)
    expect(isSpeechAudio(silenceBuf, 150)).toBe(false)

    // Loud speech-like PCM buffer (amplitude ~5000)
    const speechBuf = Buffer.alloc(1600)
    for (let i = 0; i < 800; i++) {
      speechBuf.writeInt16LE(5000, i * 2)
    }
    expect(calculatePcm16Rms(speechBuf)).toBe(5000)
    expect(isSpeechAudio(speechBuf, 150)).toBe(true)
  })

  it('filters out low-energy silence buffer in transcribe without calling STT model', async () => {
    const silenceBase64 = Buffer.alloc(3200).toString('base64') // All zeros PCM
    const result = await transcribe(silenceBase64, {
      pcm: { sampleRateHertz: 16000, channels: 1 },
    })

    expect(result.ok).toBe(true)
    expect(result.transcript).toBe('')
  })
})
