import type { FastifyInstance } from 'fastify'
import { config } from '../config.js'
import { getSessionUser } from '../session.js'

// LiveKit self-hosted helpers. The server lives on the VPS and the credentials
// are generated by bridge/kelion-livekit, so these routes are admin-only and
// provide both diagnostics and tokens for the first integration tests.

let cachedModule: typeof import('livekit-server-sdk') | undefined
async function sdk() {
  if (cachedModule) return cachedModule
  cachedModule = await import('livekit-server-sdk')
  return cachedModule
}

function httpHost(wsUrl: string): string {
  // RoomServiceClient speaks REST over http(s), not ws(s).
  return wsUrl.replace(/^ws:/, 'http:').replace(/^wss:/, 'https:')
}

export async function livekitRoutes(app: FastifyInstance): Promise<void> {
  // Admin-only health/test of the configured LiveKit server.
  app.get('/api/admin/livekit/status', async (req, reply) => {
    const user = getSessionUser(req)
    if (!user || user.role !== 'admin') return reply.code(403).send({ error: 'forbidden' })

    const { url, apiKey, apiSecret } = config.livekit
    if (!url || !apiKey || !apiSecret) {
      return reply.code(503).send({ ok: false, error: 'LiveKit not configured (LIVEKIT_URL/API_KEY/API_SECRET missing)' })
    }

    try {
      const { RoomServiceClient } = await sdk()
      const client = new RoomServiceClient(httpHost(url), apiKey, apiSecret)
      const rooms = await client.listRooms()
      return { ok: true, url, rooms: rooms.length }
    } catch (err) {
      app.log.warn({ err }, 'LiveKit status check failed')
      return reply.code(502).send({ ok: false, url, error: (err as Error).message })
    }
  })

  // Generate a short-lived token for a manual client test.
  app.post<{ Body: { identity?: string; room?: string } }>('/api/admin/livekit/token', async (req, reply) => {
    const user = getSessionUser(req)
    if (!user || user.role !== 'admin') return reply.code(403).send({ error: 'forbidden' })

    const { url, apiKey, apiSecret } = config.livekit
    if (!url || !apiKey || !apiSecret) {
      return reply.code(503).send({ error: 'LiveKit not configured' })
    }

    try {
      const { AccessToken } = await sdk()
      const identity = (req.body?.identity ?? 'kelion-test').slice(0, 64)
      const room = (req.body?.room ?? 'kelion-test-room').slice(0, 64)
      const token = new AccessToken(apiKey, apiSecret, { identity })
      token.addGrant({ roomJoin: true, room, canPublish: true, canSubscribe: true })
      const jwt = await token.toJwt()
      return { ok: true, url, identity, room, token: jwt }
    } catch (err) {
      app.log.warn({ err }, 'LiveKit token generation failed')
      return reply.code(500).send({ error: (err as Error).message })
    }
  })

  // ── VOCE FULL-DUPLEX (Adrian, 12 iul: „chatul full duplex") ──────────────────
  // Token pentru UTILIZATORUL LOGAT (nu doar admin) ca să intre în camera lui de
  // voce LiveKit. Fiecare user are o cameră PROPRIE, deterministă (numele derivă
  // din email), în care agentul de voce al lui Kelion intră și ține bucla
  // audio↔audio. Zero efect pe traseul de voce HTTP actual — e o cale nouă,
  // paralelă, pornită doar când clientul cere explicit un token de aici.
  app.post('/api/livekit/token', async (req, reply) => {
    const user = getSessionUser(req)
    if (!user) return reply.code(401).send({ error: 'unauthorized' })

    const { url, apiKey, apiSecret } = config.livekit
    if (!url || !apiKey || !apiSecret) {
      return reply.code(503).send({ error: 'LiveKit not configured' })
    }

    try {
      const { AccessToken } = await sdk()
      const identity = user.email.slice(0, 128)
      const room = voiceRoomFor(user.email)
      const token = new AccessToken(apiKey, apiSecret, {
        identity,
        // Numele afișat în cameră — pentru agentul de voce și diagnostic.
        name: user.name || user.email.split('@')[0],
        ttl: '2h',
      })
      token.addGrant({ roomJoin: true, room, canPublish: true, canSubscribe: true })
      const jwt = await token.toJwt()
      return { ok: true, url, identity, room, token: jwt }
    } catch (err) {
      app.log.warn({ err }, 'LiveKit user token generation failed')
      return reply.code(500).send({ error: (err as Error).message })
    }
  })
}

// Numele camerei de voce a unui user: determinist din email, doar caractere
// sigure. Același nume îl folosește și agentul de voce ca să știe unde să intre.
export function voiceRoomFor(email: string): string {
  return 'voice-' + email.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60)
}
