import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('Constructor monitor source contract', () => {
  it('renders persisted activity and does not retain cosmetic progress thresholds', () => {
    const source = readFileSync(new URL('./pages/Stage.tsx', import.meta.url), 'utf8')
    const admin = readFileSync(new URL('./components/admin/AdminProductie.tsx', import.meta.url), 'utf8')
    expect(source).toContain('j.continuity?.activity')
    expect(source).toContain('j.workCard')
    expect(source).toContain('constructor-work-card-${j.id}')
    expect(source).toContain('constructorJobsFromSnapshot<BuildLiveJob>')
    expect(source).toContain("setReadState('error')")
    expect(source).not.toContain('setJobs(Array.isArray(j.jobs) ? j.jobs : [])')
    expect(source).toContain('constructorPersistentEventsText(j.workCard.progress, j.workCard.evidence.eventCount)')
    expect(source).not.toContain('{j.workCard.evidence.eventCount} evenimente')
    expect(admin).toContain('j.continuity?.activity')
    expect(admin).toContain('j.workCard')
    expect(admin).toContain('Cronologia ${j.workCard.id}')
    expect(source).not.toContain('FAZE_BUILD')
    expect(source).not.toContain('Math.max(2, j.pct)')
    expect(admin).not.toContain('Math.max(2, j.pct)')
    expect(admin).not.toContain('j.continuity.heartbeat')
    expect(admin).not.toContain('j.continuity.proof')
    expect(admin).not.toContain('j.continuity.escalation')
    expect(admin).not.toContain('{j.workCard.finalResult}')
    expect(admin).toContain('constructorFinalResultText')
    expect(source).toContain("j.ci === 'local_gates'")
    expect(source).toContain('porți locale ✓')
  })
})
